config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'
  get '/contact', to: redirect('/')
  post '/contact' => 'static_pages#contact'
  get '/mandelbrot', to: 'static_pages#mandelbrot'
  get '/resume', to: 'static_pages#resume'

  # Dynamically generate a route for every file in public/notes. These all route
  # to the notes#show action, which renders the appropriate markdown file.
  #
  # These routes should stay at the bottom since this looping is probably slow.
  paths = Dir.glob("#{Rails.root}/public/notes/**/*").select do
    |f| File.file? f
  end

  paths.each do |path|
    path.slice! "#{Rails.root}/public"
    path_parts = path.split('.')

    # only allow Markdown HTML
    next unless path_parts[1..-1] == %w(html md)

    get path_parts.first, to: 'notes#show'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
# This controller handles displaying notes that I am storing in the public
# folder. The way this is done is pretty jank, and there's probably a better
# way, but for now this will do. This action currently assumes that all notes
# files are .html.md.
class NotesController < ApplicationController
  def show
    @note = File.read("#{Rails.root}/public#{request.path}.html.md")
    render layout: false
  end
end

app/controllers/static_pages_controller.rb
# This controller handles static content, loosely defined. This pretty much just
# means whatever existed on the site previously.
class StaticPagesController < ApplicationController
  def index
  end

  def contact
    ContactMailer.contact(params[:name], params[:from], params[:message]).deliver
    redirect_to :root
  end

  def mandelbrot

  end
end

app/helpers/application_helper.rb
# Helper methods available to all views
module ApplicationHelper
  # def markdown(text)
  #   renderer =
  #   ::Redcarpet::Render::HTML.new(hard_wrap: true, filter_html: true)
  #   options = {
  #     autolink: true,
  #     no_intra_emphasis: true,
  #     fenced_code_blocks: true,
  #     lax_html_blocks: true,
  #     strikethrough: true,
  #     superscript: true
  #   }

  #   ::Redcarpet::Markdown.new(renderer, options).render(text).html_safe
  # end
end

app/views/layouts/_header.html.haml
.header
  %a{ href: root_url }
    .header-main
      %h1
        %span.h-text brian mason
      %h2
        %span.h-text software engineer

  .header-nav-right
    %a{ href: resume_url } resume
    %a{ href: 'https://www.github.com/ofctlo', rel: 'me', nofollow: true } github
    %a{ href: 'https://www.linkedin.com/in/briandmason', rel: 'me', nofollow: true } linkedin
    %a{ href: 'https://plus.google.com/+BrianMason986', rel: 'me', nofollow: true } google+

app/views/layouts/application.html.haml
:ruby
  keywords = [
    'developer',
    'web developer',
    'software engineer',
    'ruby on rails developer',
    'ror developer',
    'javascript developer',
    'backbone.js developer',
    'web application development',
    'ruby on rails consulting',
    'hire ruby on rails developer',
    'brian mason',
    'brian dale mason',
    'brian d mason',
    'brian.dale.mason',
    'brian.dale.mason@gmail.com'
  ]

!!!
%html
  %head
    %title Brian Mason | Software Engineer
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %meta{ name: 'keywords', content: keywords.join(', ') }

  %body
    = render 'layouts/header'
    = yield
    = render 'layouts/google_analytics'

app/views/notes/show.html.haml
= stylesheet_link_tag 'notes'

=# markdown @note

app/views/static_pages/_contact_form.html.haml
.contact-form
  %h3
    %span.h-text contact me

  %p I'm currently available for hire, please contact me to discuss opportunities.

  = form_tag(contact_url, method: :post) do
    = text_field_tag :name, nil, placeholder: 'your name',
                                 autocomplete: 'off'
    %br

    = text_field_tag :from, nil, placeholder: 'your email address',
                                 autocomplete: 'off'
    %br

    = text_area_tag :message, nil, placeholder: 'message',
                                   autocomplete: 'off'
    %br

    = button_tag 'Contact', class: 'contact-button'

app/views/static_pages/index.html.haml
= stylesheet_link_tag 'static_pages'

.main-content
  .about
    %p
      I build things with Ruby on Rails.
    %p
      I have experience with a number of other technologies including Sinatra,
      Rspec, Javascript, jQuery, Backbone.js, React, Jasmine, HTML/CSS, Sass,
      mySQL, Sidekiq, and Git.
    %p
      When I'm not coding you can find me biking in the East Bay hills, taking
      advantage of amazing camping and backpacking, engrossed in a book, or arguing
      about politics, religion, or philosophy.

  .projects
    %h3
      %span.h-text some things I've done

    %ul
      %li.project
        = link_to 'Causes', 'https://www.causes.com'
        &middot; Worked for Causes.com building features, including a backend
        email messaging system.
      %li.project
        = link_to 'Sanisalud', 'http://www.sanisalud.org'
        &middot; Maitained and added context to non-profit's website, improved
        code quality and maintainability.
      %li.project
        = link_to 'Brello', 'https://brello.heroku.com'
        &middot; A clone of the task management software Trello that I built as an
        exercise in building a single-page app using Backbone.js.

  .contact-form
    %span brian [dot] dale [dot] mason [at] gmail [dot] com

app/views/static_pages/mandelbrot.html.haml
= stylesheet_link_tag 'static_pages'
= javascript_include_tag 'mandelbrot'

%h1.h-text The Mandelbrot and Julia Sets
%p.mandelbrot-mode-instructions
  %p
    On the left is the Mandelbrot fractal. Mouseover the Mandelbrot to generate
    the Julia fractal (on right) associated with the value at that point.
  %p
    using
    %span.h-text mouse movement
    to generate Julia set:
    %span.h-text#mode-toggle use click
  %br

  #color-toggle
    %p Set the fractal base color:
    = label :red, 'Red'
    = text_field :red, 'Red', value: 0
    = label :green, 'Green'
    = text_field :green, 'Green', value: 0
    = label :blue, 'Blue'
    = text_field :blue, 'Blue', value: 255
    %button#redraw Redraw
.pics
  .mandel
    %h2.h-text Mandelbrot set
    %canvas{ id: 'mandelbrot', height: 600, width: 600 }
  .jul
    %h2.h-text
      Julia Set K =
      %span#k-label --
    %canvas{ id: 'julia', height: 600, width: 600 }

app/views/static_pages/resume.html.haml
%a{ href: 'resume.pdf' } View pdf version

.main-header
  %h1 Brian Mason

  .contact
    brian.dale.mason@gmail.com | 708.805.5302 (US) / +1 (708) 805 5302
    %br
    www.bmason.io | www.linkedin.com/in/briandmason | www.github.com/ofctlo

.main-content
  .section
    %h2.header Summary
    .content
      I am a software engineer with experience in both frontend and backend web
      development. I’m passionate about crafting clean and maintainable code
      and systems. I love to build products that help people solve real world
      problems and I’m always curious to learn.

  .section
    %h2.header Work
    .content
      .sub-section
        %h3 Freelance Software Engineer, Unreal Group
        .dates September 2014 - Present
        .description
          &middot; Built complex interfaces using Ember and backend Rails app
          for proprietary app to manage real estate properties.
          &middot; Collaborated with remote agile team via Skype, HipChat, and
          Pivotal.

      .sub-section
        %h3 Software Engineer – Brigade
        .dates June 2014 – August 2014 | San Francisco, CA
        .description
          &middot; On small team in charge of building a communications system
          spanning the Brigade Rails application and a separate Sinatra-based
          HTTP service for asynchronous filtering, digesting, rendering, and
          sending of millions of messages per hour to our users over multiple
          mediums, including email and push notifications.

      .sub-section
        %h3 Software Engineer – Causes
        .dates Sept. 2013 – June 2014 | San Francisco, CA
        .description
          &middot; Added features, fixed bugs, and maintained Causes, one of the
          worlds largest online campaigning and advocacy platforms.
          &middot; Built email sending and tracking service using Sinatra, Redis,
          Sidekiq.

      .sub-section
        %h3 Web Application Programmer, App Academy
        .dates May 2013 – July 2013 | San Francisco, CA
        .description
          &middot; Participated in full-time web development lab. Focus on Ruby
          on Rails, HTML/CSS, JavaScript, Backbone.js and development practices
          such as Git workflows, TDD, pair programming.

  .section
    %h2.header Technical Skills
    .content
      Rails, Sinatra, Ember, Backbone.js, TDD, RSpec, Jasmine, HTML5, CSS3,
      SCSS, Postgres, Redis, Sidekiq, Git, Capistrano

  .section
    %h2.header Projects
    .content
      .subsection
        %h3 Sanisalud
        .description
          &middot; Improved maintainability of codebase and managed the website
          for an aid organization working in Nicaragua. (www.sanisalud.org)

      .subsection
        %h3 Geolatrine
        .description
          &middot; Built a simple app for tracking location and time
          information via mobile devices for use in a study of pit latrine
          emptying practices in Mombasa, Kenya.
          (www.github.com/ofctlo/geolatrine)

  .section
    %h2.header Education
    .content
      B.A., Russian Language and Literature, June 2009
      Carleton College, Northfield, MN

  .section
    %h2.header Related Coursework
    .content
      %ul
        %li Intro to Computer Science
        %li Software Design
        %li Computer Organization and Architecture
        %li Calculus II

  .section
    %h2.header Etc
    .content
      Biking, Backpacking, Hiking, Gardening, Reading: Philosophy, Physics,
      Religion, History